-- | Stable public facade for the command-line runtime.
module Agent.CLI.Runtime
    ( BuildInfo(..)
    , DevResult(..)
    , agentBuildInfo
    , afterDev
    , accountSwitchTarget
    , applyReplMode
    , buildPromptState
    , cycleReplInteraction
    , devArgs
    , devMain
    , devMainResume
    , formatMcpModelNotice
    , formatMcpModelNoticeFor
    , formatMcpProgress
    , formatBuildInfo
    , formatBuildInfoCompact
    , formatReplStatusLine
    , formatRepositoryPath
    , formatStartupTimings
    , formatTokenUsage
    , formatTokensPerSecond
    , formatUsageWithRate
    , learnAboutUserOnboardingPrompt
    , run
    , withRestoredCurrentDirectory
    ) where

import Agent.CLI.Runtime.Internal
