-- | Nestable subagent registry.
--
-- Shared state (agent map, status, mailboxes, admission count) lives in STM.
-- IO allocates ids and leases, runs scoped turns, and waits with timeouts.
module Agent.Subagents.Registry
    ( SubagentRegistry
    , SubagentLease
    , subagentLease
    , newSubagentRegistry
    , setSubagentRunner
    , setSubagentOnComplete
    , setSubagentOnSettled
    , beginRootTurn
    , abortRootTurn
    , closeSubagentRegistry
    , interruptActiveSubagents
    , resetSubagentRegistry
    , spawnSubagent
    , spawnSubagentWithCwd
    , spawnSubagentWithCwdForTurn
    , spawnSubagentWithCwdPrepared
    , spawnSubagentWithCwdPreparedForTurn
    , spawnSubagentAt
    , spawnSubagentAtForTurn
    , spawnSubagentAtPreparedForTurn
    , spawnSubagentAtWithCwdPrepared
    , spawnSubagentAtWithCwdPreparedForTurn
    , restoreSubagent
    , restoreSubagentAt
    , restoreSubagentAtStatus
    , restoreSubagentWithCwd
    , restoreSubagentAtWithCwd
    , restoreSubagentAtWithCwdStatus
    , waitSubagents
    , waitSubagentsFrom
    , waitAnyLive
    , sendInput
    , sendInputMessage
    , sendInputMessageForTurn
    , queueMessage
    , queueMessageFrom
    , queueMessageFromForTurn
    , closeSubagent
    , interruptSubagent
    , getStatus
    , getPreviousResponseId
    , getSubagentCwd
    , getSubagentIdentity
    , setPreviousResponseId
    , getTaskPath
    , resolveAgentTarget
    , listAgents
    , subagentConfig
    , setMaxConcurrent
    ) where

import Agent.Subagents.Registry.Internal.Core
import Agent.Subagents.Registry.Internal.Operations
import Agent.Subagents.Registry.Internal.Types
