-- | Opaque UUIDv7 identifiers generated by the server.
module Agent.Server.Identifier
    ( newUUIDv7Text
    , isUUIDText
    ) where

import Crypto.Random (getRandomBytes)
import Data.Bits
    ( (.&.)
    , (.|.)
    , shiftR
    )
import Data.ByteString (ByteString)
import Data.ByteString qualified as ByteString
import Data.Char (isHexDigit)
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Time.Clock.POSIX (getPOSIXTime)
import Data.Word (Word8, Word64)

-- | Generate a UUIDv7 value as lowercase text.
--
-- The first 48 bits contain Unix epoch milliseconds. Ten random bytes supply
-- the remaining entropy after the version and RFC 4122 variant bits are set.
newUUIDv7Text :: IO Text
newUUIDv7Text = do
    milliseconds <- floor . (* 1000) <$> getPOSIXTime
    entropy <- getRandomBytes 10
    let randomAt index = ByteString.index entropy index
        bytes = ByteString.pack
            [ timestampByte milliseconds 5
            , timestampByte milliseconds 4
            , timestampByte milliseconds 3
            , timestampByte milliseconds 2
            , timestampByte milliseconds 1
            , timestampByte milliseconds 0
            , 0x70 .|. (randomAt 0 .&. 0x0f)
            , randomAt 1
            , 0x80 .|. (randomAt 2 .&. 0x3f)
            , randomAt 3
            , randomAt 4
            , randomAt 5
            , randomAt 6
            , randomAt 7
            , randomAt 8
            , randomAt 9
            ]
    pure (formatUUID bytes)

isUUIDText :: Text -> Bool
isUUIDText value =
    Text.length value == 36
        && all
            (\index ->
                if index `elem` [8, 13, 18, 23]
                    then Text.index value index == '-'
                    else isHexDigit (Text.index value index))
            [0 .. 35]

timestampByte :: Word64 -> Int -> Word8
timestampByte milliseconds index =
    fromIntegral (milliseconds `shiftR` (index * 8))

formatUUID :: ByteString -> Text
formatUUID bytes =
    Text.pack $
        concat
            [ separator index <> hexByte byte
            | (index, byte) <- zip [0 :: Int ..] (ByteString.unpack bytes)
            ]
  where
    separator index
        | index `elem` [4, 6, 8, 10] = "-"
        | otherwise = ""

hexByte :: Word8 -> String
hexByte byte =
    [ digit (byte `shiftR` 4)
    , digit (byte .&. 0x0f)
    ]
  where
    digit nibble
        | nibble < 10 = toEnum (fromEnum '0' + fromIntegral nibble)
        | otherwise = toEnum (fromEnum 'a' + fromIntegral nibble - 10)
