-- | Typed PostgreSQL persistence for harness sessions.
module Agent.Store.Postgres.Session
    ( SessionMetadata(..)
    , SessionLegacyTarget(..)
    , SessionPromptSnapshot(..)
    , SessionPromptEpoch(..)
    , TranscriptEffect(..)
    , SessionTurn(..)
    , SessionUsage(..)
    , StoredSession(..)
    , StoredEvent(..)
    , StoredTurn(..)
    , LegacySession(..)
    , ConversationSearchResult(..)
    , NativeConversationSearchResult(..)
    , SessionReadImplementation(..)
    , sessionSchemaStatements
    , sessionSearchIndexStatements
    , sessionPromptEpochSchemaStatements
    , sessionTaskPlanSchemaStatements
    , createSession
    , createSessionWithInitialPromptEpoch
    , createSessionFromSnapshot
    , replaceSessionMetadata
    , setSessionTitle
    , setGeneratedSessionTitle
    , appendSessionPromptEpoch
    , appendSessionTurn
    , appendSessionTurnIndexed
    , appendSessionTurnIndexedWithPromptReset
    , appendSessionTurns
    , appendSessionTurnsClearingTaskPlan
    , loadSession
    , loadSessionWithImplementation
    , loadSessions
    , loadSessionMetadataMany
    , loadSessionMetadata
    , loadLatestSessionPromptEpoch
    , loadActiveSession
    , loadActiveSessionWithImplementation
    , SessionTurnPage(..)
    , SessionHistorySnapshot(..)
    , SessionResumeStats(..)
    , SessionTaskPlanStatus(..)
    , SessionTaskPlanItem(..)
    , SessionTaskPlan(..)
    , loadRecentSessionTurns
    , loadRecentSessionHistoryTurns
    , loadSessionTurnsBefore
    , loadSessionHistoryTurnsBefore
    , loadSessionTurnsAfter
    , loadSessionHistoryTurnsRange
    , loadSessionHistoryTurnsRangeBounded
    , loadSessionHistorySnapshot
    , loadSessionResumeStats
    , loadSessionEvents
    , listSessionMetadata
    , listSessionArchiveKeys
    , setSessionArchived
    , searchConversationTurns
    , searchConversationTurnsForBoundary
    , searchNativeConversations
    , searchNativeConversationsForBoundary
    , deleteSession
    , importLegacySession
    , withSessionAdvisoryLock
    , loadSessionTaskPlan
    , replaceSessionTaskPlan
    , clearSessionTaskPlan
    , copySessionTaskPlan
    ) where

import Agent.Store.Postgres.Session.Read
import Agent.Store.Postgres.Session.Schema
import Agent.Store.Postgres.Session.TaskPlan
import Agent.Store.Postgres.Session.Types
import Agent.Store.Postgres.Session.Write
