-- | Typed PostgreSQL persistence for harness sessions.
module Agent.Store.Postgres.Session
    ( SessionMetadata(..)
    , SessionLegacyTarget(..)
    , SessionPromptSnapshot(..)
    , SessionPromptEpoch(..)
    , TranscriptEffect(..)
    , SessionTurn(..)
    , SessionUsage(..)
    , StoredSession(..)
    , StoredEvent(..)
    , StoredTurn(..)
    , LegacySession(..)
    , ConversationSearchResult(..)
    , SessionReadImplementation(..)
    , sessionSchemaStatements
    , sessionSearchIndexStatements
    , sessionPromptEpochSchemaStatements
    , createSession
    , createSessionWithInitialPromptEpoch
    , createSessionFromSnapshot
    , replaceSessionMetadata
    , appendSessionPromptEpoch
    , appendSessionTurn
    , appendSessionTurnIndexed
    , appendSessionTurnIndexedWithPromptReset
    , appendSessionTurns
    , loadSession
    , loadSessionWithImplementation
    , loadSessions
    , loadSessionMetadata
    , loadLatestSessionPromptEpoch
    , loadActiveSession
    , loadActiveSessionWithImplementation
    , SessionTurnPage(..)
    , SessionResumeStats(..)
    , loadRecentSessionTurns
    , loadSessionTurnsBefore
    , loadSessionTurnsAfter
    , loadSessionResumeStats
    , loadSessionEvents
    , listSessionMetadata
    , searchConversationTurns
    , deleteSession
    , importLegacySession
    , withSessionAdvisoryLock
    ) where

import Agent.Store.Postgres.Session.Read
import Agent.Store.Postgres.Session.Schema
import Agent.Store.Postgres.Session.Types
import Agent.Store.Postgres.Session.Write
