-- | Model Context Protocol clients over stdio and Streamable HTTP.
--
-- Each configured server is started once, its protocol era negotiated
-- (@server/discover@ for revision 2026-07-28, the @initialize@ handshake for
-- earlier revisions), and queried for its tools and (when negotiated)
-- Skills-over-MCP metadata. The returned handlers share the retained client;
-- 'closeMcpFleet' must run after all loops and subagents using those handlers
-- have stopped.
module Agent.MCP
    ( McpServerConfig(..)
    , McpConnectionIdentity(..)
    , McpProtocolPreference(..)
    , McpProtocolEra(..)
    , McpServerInfo(..)
    , McpServerCapabilities(..)
    , McpListCapability(..)
    , McpResourcesCapability(..)
    , McpHostHooks(..)
    , McpCredentialProvider(..)
    , defaultMcpHostHooks
    , McpLogLevel(..)
    , mcpLogLevelText
    , McpIcon(..)
    , McpRoot(..)
    , McpSamplingMessage(..)
    , McpModelHint(..)
    , McpModelPreferences(..)
    , McpSamplingRequest(..)
    , McpSamplingResult(..)
    , McpTaskStatus(..)
    , McpTaskInputRequest(..)
    , McpTask(..)
    , McpTaskList(..)
    , McpServerEvent(..)
    , McpElicitRequest(..)
    , McpElicitMode(..)
    , McpElicitResult(..)
    , McpInitState(..)
    , McpServerStatus(..)
    , McpToolRegistration(..)
    , McpSkillsCapability(..)
    , McpSkillRegistration(..)
    , McpSkillEntry(..)
    , McpSkillResources(..)
    , McpSkillResource(..)
    , McpResourceContent(..)
    , McpResource(..)
    , McpResourceTemplate(..)
    , McpPrompt(..)
    , McpPromptArgument(..)
    , McpPromptMessage(..)
    , McpPromptResult(..)
    , McpCompletion(..)
    , McpCompletionRef(..)
    , McpProgress(..)
    , McpError(..)
    , renderMcpError
    , McpFleet(..)
    , McpSupervisor
    , McpFleetLease(..)
    , newMcpSupervisor
    , newMcpSupervisorWith
    , acquireMcpFleet
    , acquireMcpFleetWithProgress
    , acquireMcpFleetProgressive
    , acquireMcpFleetWithInMemory
    , acquireMcpFleetProgressiveWithInMemory
    , releaseMcpFleetLease
    , closeMcpSupervisor
    , restartMcpSupervisor
    , startMcpFleet
    , startMcpFleetWithProgress
    , startMcpFleetWithProgressHooks
    , startMcpFleetWithInMemory
    , startMcpFleetProgressiveWithInMemoryHooks
    , McpToolServer(..)
    , McpTool(..)
    , emptyServerCapabilities
    , McpCallToolRequest(..)
    , McpCallToolResult(..)
    , startMcpFleetProgressive
    , startMcpFleetProgressiveHooks
    , closeMcpFleet
    , mcpFleetTools
    , mcpFleetToolsForArtifactDirectory
    , mcpFleetRegistrationsForArtifactDirectory
    , mcpFleetMetaTools
    , mcpFleetMetaToolsForArtifactDirectory
    , McpToolDiscovery
    , newMcpToolDiscovery
    , mcpFleetCodexToolsForArtifactDirectory
    , mcpFleetGrokMetaTools
    , mcpFleetGrokMetaToolsForArtifactDirectory
    , mcpFleetResourceTools
    , mcpFleetStatuses
    , mcpFleetServerInfos
    , mcpFleetInstructions
    , mcpFleetSkillRegistrations
    , mcpFleetGetSkill
    , mcpFleetReadResource
    , mcpFleetListResources
    , mcpFleetListResourceTemplates
    , mcpFleetListPrompts
    , mcpFleetGetPrompt
    , mcpFleetComplete
    , normalizeMcpToolResult
    , renderMcpPromptResult
    , decodeHttpMcpResponse
    , modernProtocolVersion
    , supportedLegacyVersions
    , InProcessMcpServer
    , InProcessMcpApproval
    , createInProcessMcpServer
    , inProcessMcpToolNames
    , handleInProcessMcpMessage
    , inProcessMcpToolServer
    , handleToolServerMessage
    ) where

import Agent.MCP.Client
    ( McpCompletionRef(..)
    , decodeHttpMcpResponse
    , modernProtocolVersion
    , normalizeMcpToolResult
    , renderMcpPromptResult
    , supportedLegacyVersions
    )
import Agent.MCP.InProcess
    ( InProcessMcpApproval
    , inProcessMcpToolServer
    , handleToolServerMessage
    , InProcessMcpServer
    , createInProcessMcpServer
    , handleInProcessMcpMessage
    , inProcessMcpToolNames
    )
import Agent.MCP.Fleet
    ( McpToolDiscovery
    , newMcpToolDiscovery
    , mcpFleetCodexToolsForArtifactDirectory
    , startMcpFleetWithInMemory
    , startMcpFleetProgressiveWithInMemoryHooks
    , closeMcpFleet
    , mcpFleetComplete
    , mcpFleetGetPrompt
    , mcpFleetGetSkill
    , mcpFleetGrokMetaTools
    , mcpFleetGrokMetaToolsForArtifactDirectory
    , mcpFleetInstructions
    , mcpFleetListPrompts
    , mcpFleetListResourceTemplates
    , mcpFleetListResources
    , mcpFleetMetaTools
    , mcpFleetMetaToolsForArtifactDirectory
    , mcpFleetReadResource
    , mcpFleetResourceTools
    , mcpFleetServerInfos
    , mcpFleetSkillRegistrations
    , mcpFleetStatuses
    , mcpFleetRegistrationsForArtifactDirectory
    , mcpFleetTools
    , mcpFleetToolsForArtifactDirectory
    , startMcpFleet
    , startMcpFleetProgressive
    , startMcpFleetProgressiveHooks
    , startMcpFleetWithProgress
    , startMcpFleetWithProgressHooks
    )
import Agent.MCP.Supervisor
    ( acquireMcpFleet
    , acquireMcpFleetProgressive
    , acquireMcpFleetProgressiveWithInMemory
    , acquireMcpFleetWithInMemory
    , acquireMcpFleetWithProgress
    , closeMcpSupervisor
    , newMcpSupervisor
    , newMcpSupervisorWith
    , releaseMcpFleetLease
    , restartMcpSupervisor
    )
import Agent.MCP.Types
    ( McpToolServer(..)
    , McpCredentialProvider(..)
    , McpTool(..)
    , emptyServerCapabilities
    , McpCallToolRequest(..)
    , McpCallToolResult(..)
    , McpCompletion(..)
    , McpElicitMode(..)
    , McpElicitRequest(..)
    , McpElicitResult(..)
    , McpError(..)
    , McpFleet(..)
    , McpFleetLease(..)
    , McpHostHooks(..)
    , McpIcon(..)
    , McpInitState(..)
    , McpListCapability(..)
    , McpLogLevel(..)
    , mcpLogLevelText
    , McpModelHint(..)
    , McpModelPreferences(..)
    , McpProgress(..)
    , McpPrompt(..)
    , McpPromptArgument(..)
    , McpPromptMessage(..)
    , McpPromptResult(..)
    , McpProtocolEra(..)
    , McpProtocolPreference(..)
    , McpResource(..)
    , McpResourceContent(..)
    , McpResourceTemplate(..)
    , McpResourcesCapability(..)
    , McpRoot(..)
    , McpSamplingMessage(..)
    , McpSamplingRequest(..)
    , McpSamplingResult(..)
    , McpServerCapabilities(..)
    , McpServerConfig(..)
    , McpConnectionIdentity(..)
    , McpServerEvent(..)
    , McpServerInfo(..)
    , McpServerStatus(..)
    , McpSkillEntry(..)
    , McpSkillRegistration(..)
    , McpSkillResource(..)
    , McpSkillResources(..)
    , McpSkillsCapability(..)
    , McpSupervisor
    , McpTask(..)
    , McpTaskInputRequest(..)
    , McpTaskList(..)
    , McpTaskStatus(..)
    , McpToolRegistration(..)
    , defaultMcpHostHooks
    , renderMcpError
    )
